logging:
  level:
    org:
      springframework:
        security:
          web: trace
org:
  seminify:
    upload:
      path: upload
spring:
  datasource:
    url: jdbc:mariadb://localhost/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
